### ISSUE TITLE
Test on Firefox and potentially update README warning about selection support.

### ISSUE THREAD

**Issue by timabbott** [fregante/text-field-edit#11]
Thanks for this great library!  The API is nice and clean; we're [planning to use this](https://github.com/zulip/zulip/pull/18922) in [Zulip](https://github.com/zulip/zulip).

It looks like [the Firefox bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1220696) that is [linked from the README](https://github.com/fregante/text-field-edit#readme) has been fixed!  It seems worth testing whether that indeed fixes undo support for this library in Firefox, and then updating the README to say e.g. "Undo support works in Firefox >= X", where X is the release that bug was fixed in.

**Comment by fregante** [comment]
Indeed it appears to be working: https://codepen.io/fregante/pen/dyROWxq

**Comment by fregante** [comment]
I'll make some changes and post them soon.

Thanks for the report and for the sponsorship! Glad you found this useful
