### ISSUE TITLE
Add textFieldEdit.replace option that doesn't change selection

### ISSUE THREAD

**Issue by timabbott** [fregante/text-field-edit#14]
In some situations, you want to programmatically edit text in a textbox without generating a selection.  (E.g. one use case I have for this is inserting a placeholder into the textarea while we wait to fetch data from the server, and then replacing the placeholder with the value returned from the server).  I'd want to use `textFieldEdit.replace` for this, but it also selects content, which we don't want.

```
textFieldEdit.replace(field, searchValue, replacement)
Finds and replaces strings and regular expressions in the field’s value, like field.value = field.value.replace() but leaves the last replacement selected like a text editor would.
```

It'd be nice if there were either a variant to do this or a way to pass an additional option to disable the selection part of the function.

**Comment by fregante** [comment]
It sounds like you need the `set` method. Does that behave the way you want?

**Comment by fregante** [comment]
> disable the selection part of the function.

To address this specifically, the core API (`insertText`) works exactly like a "paste" would: It injects text at the cursor or replaces a specific **selection.** 

This means that the `replace` method must select the matched word to replace it; This also moves the cursor.

If you want to disable the selection, you can just set `field.selectionEnd = field.selectionStart` to place the cursor at the end of the last selection **or* `field.selectionEnd = Infinity` to place it at the end.

I'd probably accept a PR to add a `cursor: "select" | "after-select"` option to toggle this line though:

https://github.com/fregante/text-field-edit/blob/17074dd905ca57cd8d6658ef721baa94f5ba2d2e/index.ts#L95-L97

The option could also be `cursor: "select" | "after-select" | "preserve"` but that's slightly more involved.

**Comment by leevigraham** [comment]
@fregante I think what @timabbott is referring to is it selects the text after replacement… not during the replacement process. Copy + Paste in textareas places the cursor at the end of the replacement after paste. 

I would also like an option to change the current behaviour.

**Comment by fregante** [comment]
You're right, this is the line: https://github.com/fregante/text-field-edit/blob/7f26e5a5fb69e1e621b9fa14c1b17387df4afb05/index.ts#L104-L105

The idea when implementing it was to have it redirect the user’s focus to the replacement, but I suppose that's not always wanted.

PR welcome to add option, it would have to add a condition around that line. I think the cursor however will still be placed after the last replacement. Preserving the position would be more involved:

- was it before the replacement? set its initial index
- was it in the replaced text? set it after the replacement (already happens)
- was it after the last replacement? set the initial index + the drift
- was it between 2 replacements? set the initial index + the drift as it was between those 2 replacements

I'll look into this specific logic later though.

**Comment by leevigraham** [comment]
@timabbott I was facing the same issue when implementing a Github like drag drop file uploader. In the end I ended up doing a set:

```
textAreaValue = textAreaValue.replace(placeholderText, newText);
textFieldEdit.set(textarea, textAreaValue);
```

Not sure how this will affect UX and cursor position tho.
