### ISSUE TITLE
Default "index" lookups for the main are deprecated for ES modules

### ISSUE THREAD

**Issue by kevinrenskers** [fregante/text-field-edit#15]
When I do something like `import { insert, wrapSelection, getSelection } from "text-field-edit"`, I get the following warning in my Node application:

`DeprecationWarning: No "main" or "exports" field defined in the package.json for /opt/www/node_modules/text-field-edit/ resolving the main entry point "index.js". Default "index" lookups for the main are deprecated for ES modules.`

Is this something that can be fixed?

Thanks for this amazing library btw!

**Comment by fregante** [comment]
What tool is outputting that warning? Is it Node itself?

**Comment by kevinrenskers** [comment]
Yeah, it's Node itself, when I am building my SvelteKit application that uses text-field-edit.

**Comment by fregante** [comment]
Thanks! It'll be fixed in the next release

**Comment by kevinrenskers** [comment]
Thanks! Any idea when we can expect a new release?

**Comment by fregante** [comment]
2023
