### ISSUE TITLE
textFieldEdit.set(textarea, "") doesn’t change the textarea content on Firefox

### ISSUE THREAD

**Issue by leafac** [fregante/text-field-edit#16]
This seems to be an oddly specific situation. It only happens on Firefox (I tested and it doesn’t happen on Safari, Chrome, and Edge). It only happens if you’re trying to set the textarea to an empty string (`textFieldEdit.set(textarea, "Hello")`, for example, works fine). I tested in macOS & Windows, both running Firefox 97 (the latest at the time of this writing).

As far as I can tell, the issue happens because `document.execCommand('insertText', false, text)` returns `true` when `text === ""`, so text-field-edit doesn’t call the `insertTextFirefox()` function, but Firefox hasn’t really changed the value of the textarea 🤷

What do you think would be the appropriate solution here? There are so many edge cases and compatibility concerns to consider…

**Workaround:** For the time being I’m resorting to:

```javascript
textarea.value = "";
textFieldEdit.set(textarea, "");
```

It may mess with the undo history, but at least it fires the `input` event.

**Comment by leevigraham** [comment]
@leafac This also fails on newer Firefox browsers (tested on 98.0b10 (64-bit)) that support `document.execCommand`. 

An alternative is to use `document.execCommand('delete')` to delete the selected text when there is an empty value passed.

**Comment by fregante** [comment]
Thanks for the tip! That seems to work and it's been fixed in version 9001. It looks like Firefox thinks `insert ""` should do nothing.  

This bug affected both `set(el, "")` and `insert(el, "")` since they use the same command.

**Comment by leafac** [comment]
Thanks for looking into this!
