### ISSUE TITLE
Bug report: Selection is not restored as expected when calling `wrapFieldSelection` with different left and right wrapping strings

### ISSUE THREAD

**Issue by N-Shar-ma** [fregante/text-field-edit#31]
This bug seems to have been introduced in the latest version v4.1.0, specifically in this [commit](https://github.com/fregante/text-field-edit/commit/fb45ad0f568b85e8e26028bff4076519b7e3ba52#diff-dcdc3e0b3362edb8fec2a51d3fa51f8fb8af8f70247e06d9887fa934834c9122).

The following line
https://github.com/fregante/text-field-edit/blob/bac101dc21128caaba384d661c29457bae9dcc87/index.ts#L97
should replace `wrapEnd` with `wrap` and instead be:
```
field.selectionEnd = selectionEnd! + wrap.length;
```
like it was before the linked commit.

@fregante Would you like me to make a PR fixing this?

**Comment by fregante** [comment]
Yes please! Can you also alter one of the tests so that this error becomes visible? e.g. call `wrap(field, '<<', '>')`
