### ISSUE TITLE
Support draft-js editor

### ISSUE THREAD

**Issue by FSou1** [fregante/text-field-edit#8]
Greetings,

I've been using `insert-text-at-cursor` package for inserting text into default textarea/input components and it works great.

Unfortunately, it doesn't work well at sites that use the [draft-js](https://draftjs.org/) editor (e.g. reddit or facebook).

I've tried to use your package but it doesn't work well either.

Here is a workaround that works for draft-js.

Is there a chance to support this editor?

This is the minimum valuable code that inserts a text at cursor with draft-js:

```
function addTextToDraftJs(element, text) {
    var textEvent = document.createEvent('TextEvent');
    textEvent.initTextEvent ('textInput', true, true, null, text);                    
    element.dispatchEvent(textEvent);
}

addTextToDraftJs(document.activeElement, 'it works');
```

Thx.

**Comment by fregante** [comment]
Sorry I have no intention of supporting non-native fields. The API is completely different
